laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('home/produtos', 'HomeController@getProdutosHome')->name('getProdutosHome');
    Route::get('home/marcas', 'HomeController@getMarcasHome')->name('getMarcasHome');
    Route::post('newsletter', 'HomeController@postNewsletter')->name('newsletter.post');
    Route::get('produtos/{linha}', 'ProdutosController@index')->name('produtos'); //ok
    Route::get('produtos/{linha}/produto/{produto}', 'ProdutosController@showProduto')->name('produtos.show');
    Route::get('produtos/{linha}/busca', 'ProdutosController@busca')->name('produtos.busca'); //ok
    Route::get('produtos/{linha}/lancamentos', 'ProdutosController@filtroLancamentos')->name('produtos.lancamentos');
    Route::get('produtos/{linha}/getProdutos', 'ProdutosController@getProdutos')->name('produtos.getProdutos');
    Route::get('produtos/{linha}/categorias', 'ProdutosController@indexCategorias')->name('produtos.categorias');
    Route::get('produtos/{linha}/categorias/letra/{letra}', 'ProdutosController@filtroLetras')->name('produtos.letra');
    Route::get('produtos/{linha}/marcas/{marca}', 'ProdutosController@filtroMarcas')->name('produtos.marcas');
    Route::get('produtos/{linha}/{categoria}/{marca_slug?}', 'ProdutosController@filtro')->name('produtos.filtro');
    Route::get('produtos/pdf/{produto}', 'ProdutosController@openPdf')->name('produtos.pdf');
    Route::get('orcamentos', 'OrcamentosController@index')->name('orcamentos');
    Route::post('orcamentos/adicionar/{linha}/{produto}', 'OrcamentosController@adicionar')->name('orcamentos.adicionar');
    Route::get('orcamentos/atualizar/{produto}', 'OrcamentosController@atualizar')->name('orcamentos.atualizar');
    Route::get('orcamentos/excluir/{produto}', 'OrcamentosController@excluir')->name('orcamentos.excluir');
    Route::get('orcamentos/{cliente}', 'OrcamentosController@post')->name('orcamentos.post');
    Route::get('marcas', 'MarcasController@index')->name('marcas');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('novidades', 'NovidadesController@index')->name('novidades');
    Route::get('novidades/{novidade}', 'NovidadesController@show')->name('novidades.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('contato-footer', 'ContatoController@postFooter')->name('contato-footer.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('busca', 'BuscaController@buscar')->name('busca'); //ok
    Route::get('busca/{linha}/categorias/{letra}', 'BuscaController@getCategorias')->name('getCategorias'); //ok
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Auth Clientes
    Route::group([
        'prefix'    => 'cliente',
        'namespace' => 'Cliente'
    ], function () {
        Route::post('login', 'AuthController@login')->name('cliente.login');
        Route::get('logout', 'AuthController@logout')->name('cliente.logout');
        Route::post('cadastro', 'AuthController@create')->name('cliente.cadastro');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('home-banners', 'HomeBannersController');
        Route::resource('home-destaques', 'HomeDestaquesController', ['only' => ['index', 'update']]);
        Route::resource('home-diferenciais', 'HomeDiferenciaisController');
        Route::resource('marcas', 'MarcasController');
        Route::get('linhas', 'LinhasController@index')->name('painel.linhas.index');
        Route::resource('linhas.categorias', 'CategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/linhas/{linha}/categorias', 'ProdutosController@getCategorias')->name('painel.produtos.linhas.categorias');
        Route::get('produtos/{produto}/desenho/delete', 'ProdutosController@deleteDesenho')->name('painel.produtos.desenho.delete');
        Route::get('produtos/{produto}/manual/delete', 'ProdutosController@deleteManual')->name('painel.produtos.manual.delete');
        Route::get('produtos/{produto}/variacoes/delete', 'ProdutosController@deleteImagem')->name('painel.produtos.variacoes.delete');
        Route::resource('clientes', 'ClientesController', ['only' => ['index', 'destroy']]);
        Route::get('clientes/export', 'ClientesController@export')->name('painel.clientes.export');
        Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::get('empresa/imagens/clear', [
            'as'   => 'painel.empresa.imagens.clear',
            'uses' => 'EmpresaImagensController@clear'
        ]);
        Route::resource('empresa/imagens', 'EmpresaImagensController', ['parameters' => ['imagens' => 'empresa_imagens']]);
        Route::resource('empresa/diferenciais', 'EmpresaDiferenciaisController');
        Route::resource('categorias-novidades', 'CategoriasNovidadesController');
        Route::resource('novidades', 'NovidadesController');
        Route::get('orcamentos/{orcamento}/toggle', ['as' => 'painel.orcamentos.toggle', 'uses' => 'OrcamentosController@toggle']);
        Route::resource('orcamentos', 'OrcamentosController');
        Route::resource('orcamentos-contatos', 'ContatosOrcamentosController');

        Route::get('newsletter', 'NewsletterController@index')->name('painel.newsletter.index');
        Route::get('newsletter/export', 'NewsletterController@export')->name('painel.newsletter.export');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:cache');
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('clear-compiled');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NewsletterRequest;
use App\Models\AceiteDeCookies;
use App\Models\Contato;
use App\Models\HomeBanner;
use App\Models\HomeDestaque;
use App\Models\HomeDiferencial;
use App\Models\Marca;
use App\Models\Newsletter;
use App\Models\Novidade;
use App\Models\Produto;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class HomeController extends Controller
{
    public function index(Request $request)
    {
        $banners = HomeBanner::ordenados()->get();
        $destaques = HomeDestaque::first();
        $diferenciais = HomeDiferencial::ordenados()->get();
        $novidades = Novidade::join('categorias_novidades', 'categorias_novidades.id', '=', 'novidades.categoria_id')
            ->select('categorias_novidades.id as cat_id', 'categorias_novidades.slug as cat_slug', 'categorias_novidades.titulo as cat_titulo', 'novidades.id', 'novidades.data', 'novidades.slug', 'novidades.titulo', 'novidades.capa')
            ->orderBy('data', 'desc')->take(3)->get();

        $verificacao = AceiteDeCookies::where('ip', $request->ip())->first();

        return view('frontend.home', compact('banners', 'destaques', 'diferenciais', 'novidades', 'verificacao'));
    }

    public function getProdutosHome()
    {
        $produtos = Produto::home()
            ->join('categorias', 'categorias.id', '=', 'produtos.categoria_id')
            ->join('linhas', 'linhas.id', '=', 'categorias.linha_id')
            ->select('produtos.*', 'linhas.id as linha_id', 'linhas.slug as linha_slug', 'linhas.titulo as linha_titulo')
            ->get();

        return response()->json(['produtos' => $produtos]);
    }

    public function getMarcasHome()
    {
        $marcas = Marca::get();

        return response()->json(['marcas' => $marcas]);
    }

    public function postNewsletter(NewsletterRequest $request, Newsletter $newsletter)
    {
        $data = $request->all();

        $newsletter->create($data);
        $this->sendMail($data);

        return redirect()->route('home')->with('success', true);
    }

    private function sendMail($data)
    {
        if (!$email = Contato::first()->email) {
            return false;
        }

        Mail::send('emails.newsletter', $data, function ($m) use ($email, $data) {
            $m->to($email, config('app.name'))
                ->subject('[CONTATO] ' . config('app.name'))
                ->replyTo($data['email'], $data['nome']);
        });
    }

    public function postCookies(Request $request)
    {
        $input = $request->all();
        $input['ip'] = $request->ip();

        AceiteDeCookies::create($input);

        return redirect('/');
    }
}

laravel/resources/views/painel/home/diferenciais/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Home - Diferenciais |</small> Adicionar Diferencial</h2>
</legend>

{!! Form::open(['route' => 'painel.home-diferenciais.store', 'files' => true]) !!}

@include('painel.home.diferenciais.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/home/diferenciais/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Home - Diferenciais |</small> Editar Diferencial</h2>
</legend>

{!! Form::model($diferencial, [
'route' => ['painel.home-diferenciais.update', $diferencial->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.home.diferenciais.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/home/diferenciais/form.blade.php
@include('painel.common.flash')

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/home/diferenciais/'.$diferencial->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('link', 'Link (opcional)') !!}
    {!! Form::text('link', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.home-diferenciais.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/home/diferenciais/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        Home - Diferenciais
        <a href="{{ route('painel.home-diferenciais.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Diferencial</a>
    </h2>
</legend>


@if(!count($diferenciais))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="home_diferenciais">
    <thead>
        <tr>
            <th>Ordenar</th>
            <th>Imagem</th>
            <th>Título</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($diferenciais as $diferencial)
        <tr class="tr-row" id="{{ $diferencial->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            <td><img src="{{ asset('assets/img/home/diferenciais/'.$diferencial->imagem) }}" style="width: 100%; max-width:150px;" alt=""></td>
            <td>{{ $diferencial->titulo }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.home-diferenciais.destroy', $diferencial->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.home-diferenciais.edit', $diferencial->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection