laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('home/produtos', 'HomeController@getProdutosHome')->name('getProdutosHome');
    Route::get('home/marcas', 'HomeController@getMarcasHome')->name('getMarcasHome');
    Route::post('newsletter', 'HomeController@postNewsletter')->name('newsletter.post');
    Route::get('produtos/{linha}', 'ProdutosController@index')->name('produtos'); //ok
    Route::get('produtos/{linha}/produto/{produto}', 'ProdutosController@showProduto')->name('produtos.show');
    Route::get('produtos/{linha}/busca', 'ProdutosController@busca')->name('produtos.busca'); //ok
    Route::get('produtos/{linha}/lancamentos', 'ProdutosController@filtroLancamentos')->name('produtos.lancamentos');
    Route::get('produtos/{linha}/getProdutos', 'ProdutosController@getProdutos')->name('produtos.getProdutos');
    Route::get('produtos/{linha}/categorias', 'ProdutosController@indexCategorias')->name('produtos.categorias');
    Route::get('produtos/{linha}/categorias/letra/{letra}', 'ProdutosController@filtroLetras')->name('produtos.letra');
    Route::get('produtos/{linha}/marcas/{marca}', 'ProdutosController@filtroMarcas')->name('produtos.marcas');
    Route::get('produtos/{linha}/{categoria}/{marca_slug?}', 'ProdutosController@filtro')->name('produtos.filtro');
    Route::get('produtos/pdf/{produto}', 'ProdutosController@openPdf')->name('produtos.pdf');
    Route::get('orcamentos', 'OrcamentosController@index')->name('orcamentos');
    Route::post('orcamentos/adicionar/{linha}/{produto}', 'OrcamentosController@adicionar')->name('orcamentos.adicionar');
    Route::get('orcamentos/atualizar/{produto}', 'OrcamentosController@atualizar')->name('orcamentos.atualizar');
    Route::get('orcamentos/excluir/{produto}', 'OrcamentosController@excluir')->name('orcamentos.excluir');
    Route::get('orcamentos/{cliente}', 'OrcamentosController@post')->name('orcamentos.post');
    Route::get('marcas', 'MarcasController@index')->name('marcas');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('novidades', 'NovidadesController@index')->name('novidades');
    Route::get('novidades/{novidade}', 'NovidadesController@show')->name('novidades.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('contato-footer', 'ContatoController@postFooter')->name('contato-footer.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('busca', 'BuscaController@buscar')->name('busca'); //ok
    Route::get('busca/{linha}/categorias/{letra}', 'BuscaController@getCategorias')->name('getCategorias'); //ok
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Auth Clientes
    Route::group([
        'prefix'    => 'cliente',
        'namespace' => 'Cliente'
    ], function () {
        Route::post('login', 'AuthController@login')->name('cliente.login');
        Route::get('logout', 'AuthController@logout')->name('cliente.logout');
        Route::post('cadastro', 'AuthController@create')->name('cliente.cadastro');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('home-banners', 'HomeBannersController');
        Route::resource('home-destaques', 'HomeDestaquesController', ['only' => ['index', 'update']]);
        Route::resource('home-diferenciais', 'HomeDiferenciaisController');
        Route::resource('marcas', 'MarcasController');
        Route::get('linhas', 'LinhasController@index')->name('painel.linhas.index');
        Route::resource('linhas.categorias', 'CategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/linhas/{linha}/categorias', 'ProdutosController@getCategorias')->name('painel.produtos.linhas.categorias');
        Route::get('produtos/{produto}/desenho/delete', 'ProdutosController@deleteDesenho')->name('painel.produtos.desenho.delete');
        Route::get('produtos/{produto}/manual/delete', 'ProdutosController@deleteManual')->name('painel.produtos.manual.delete');
        Route::get('produtos/{produto}/variacoes/delete', 'ProdutosController@deleteImagem')->name('painel.produtos.variacoes.delete');
        Route::resource('clientes', 'ClientesController', ['only' => ['index', 'destroy']]);
        Route::get('clientes/export', 'ClientesController@export')->name('painel.clientes.export');
        Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::get('empresa/imagens/clear', [
            'as'   => 'painel.empresa.imagens.clear',
            'uses' => 'EmpresaImagensController@clear'
        ]);
        Route::resource('empresa/imagens', 'EmpresaImagensController', ['parameters' => ['imagens' => 'empresa_imagens']]);
        Route::resource('empresa/diferenciais', 'EmpresaDiferenciaisController');
        Route::resource('categorias-novidades', 'CategoriasNovidadesController');
        Route::resource('novidades', 'NovidadesController');
        Route::get('orcamentos/{orcamento}/toggle', ['as' => 'painel.orcamentos.toggle', 'uses' => 'OrcamentosController@toggle']);
        Route::resource('orcamentos', 'OrcamentosController');
        Route::resource('orcamentos-contatos', 'ContatosOrcamentosController');

        Route::get('newsletter', 'NewsletterController@index')->name('painel.newsletter.index');
        Route::get('newsletter/export', 'NewsletterController@export')->name('painel.newsletter.export');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:cache');
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('clear-compiled');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/CategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoriasRequest;
use App\Http\Requests\LinhasRequest;
use App\Models\Categoria;
use App\Models\Linha;

class CategoriasController extends Controller
{
    public function index(Linha $linhas)
    {
        $categorias = Categoria::linha($linhas->id)->orderBy('titulo', 'asc')->paginate(15);

        return view('painel.linhas.categorias.index', compact('linhas', 'categorias'));
    }

    public function create(Linha $linhas)
    {
        return view('painel.linhas.categorias.create', compact('linhas'));
    }

    public function store(LinhasRequest $request, Linha $linhas)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');
            $input['linha_id'] = $linhas->id;

            $count = count(Categoria::where('slug', $input['slug'])->where('linha_id', $input['linha_id'])->get());

            if ($count == 0) {
                Categoria::create($input);
            } else {
                return back()->withErrors(['Erro ao adicionar registro: Verifique se esse registro já existe']);
            }

            return redirect()->route('painel.linhas.categorias.index', $linhas->id)->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Linha $linhas, Categoria $categorias)
    {
        $categoria = $categorias;

        return view('painel.linhas.categorias.edit', compact('linhas', 'categoria'));
    }

    public function update(CategoriasRequest $request, Linha $linhas, Categoria $categorias)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $categorias->update($input);

            return redirect()->route('painel.linhas.categorias.index', $linhas->id)->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Linha $linhas, Categoria $categorias)
    {
        try {
            $categorias->delete();

            return redirect()->route('painel.linhas.categorias.index', $linhas->id)->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CategoriasNovidadesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoriasNovidadesRequest;
use App\Models\CategoriaNovidade;

class CategoriasNovidadesController extends Controller
{
    public function index()
    {
        $categorias = CategoriaNovidade::orderBy('titulo', 'desc')->get();

        return view('painel.novidades.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.novidades.categorias.create');
    }

    public function store(CategoriasNovidadesRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $count = count(CategoriaNovidade::where('slug', $input['slug'])->get());

            if ($count == 0) {
                CategoriaNovidade::create($input);
            } else {
                return back()->withErrors(['Erro ao adicionar registro: Verifique se esse registro já existe']);
            }

            return redirect()->route('painel.categorias-novidades.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(CategoriaNovidade $categoria)
    {
        return view('painel.novidades.categorias.edit', compact('categoria'));
    }

    public function update(CategoriasNovidadesRequest $request, CategoriaNovidade $categoria)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $categoria->update($input);

            return redirect()->route('painel.categorias-novidades.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(CategoriaNovidade $categoria)
    {
        try {
            $categoria->delete();

            return redirect()->route('painel.categorias-novidades.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ClientesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\Cliente;
use Maatwebsite\Excel\Facades\Excel;

class ClientesController extends Controller
{
    public function index()
    {
        $clientes = Cliente::orderBy('nome', 'ASC')->paginate(10);

        return view('painel.clientes.index', compact('clientes'));
    }

    public function destroy(Cliente $cliente)
    {
        try {
            $cliente->delete();

            return redirect()->route('painel.clientes.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }

    public function export()
    {
        $row[] = array('Data', 'Nome', 'E-mail', 'Telefone', 'Empresa');

        $exportDados = Cliente::all();

        foreach ($exportDados as $dados) {
            $row[] = array(
                $dados->created_at,
                $dados->nome,
                $dados->email,
                $dados->telefone,
                $dados->empresa
            );
        }

        return Excel::create('Clientes - Cadastros', function ($excel) use ($row) {
            $excel->setTitle('Cadastros');
            $excel->sheet('Cadastros', function ($sheet) use ($row) {
                $sheet->fromArray($row, null, 'A1', false, false);
            });
        })->export('csv');
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConfiguracoesRequest;
use App\Models\Configuracao;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracao::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracao $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracao::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContatoRequest;
use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {
            $input = $request->all();

            $contato->update($input);

            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/EmpresaController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\EmpresaRequest;
use App\Models\Empresa;

class EmpresaController extends Controller
{
    public function index()
    {
        $empresa = Empresa::first();

        return view('painel.empresa.edit', compact('empresa'));
    }

    public function update(EmpresaRequest $request, Empresa $empresa)
    {
        try {
            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Empresa::upload_capa();

            $empresa->update($input);

            return redirect()->route('painel.empresa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*', 'painel.politica-de-privacidade*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>
                            <a href="{{ route('painel.politica-de-privacidade.index') }}">Política de Privacidade</a>
                        </li>
                        <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>
                            <a href="{{ route('painel.aceite-de-cookies') }}">Relatório de Cookies</a>
                        </li>
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">

    <li class="dropdown @if(Tools::routeIs(['painel.home-banners*', 'painel.home-diferenciais*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.home-banners*')) class="active" @endif>
                <a href="{{ route('painel.home-banners.index') }}">Banners</a>
            </li>
            <li @if(Tools::routeIs('painel.home-destaques*')) class="active" @endif>
                <a href="{{ route('painel.home-destaques.index') }}">Links Destaques</a>
            </li>
            <li @if(Tools::routeIs('painel.home-diferenciais*')) class="active" @endif>
                <a href="{{ route('painel.home-diferenciais.index') }}">Diferenciais</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.marcas*')) class="active" @endif>
        <a href="{{ route('painel.marcas.index') }}">Marcas</a>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.linhas-de-produtos*', 'painel.produtos*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Produtos <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.linhas*')) class="active" @endif>
                <a href="{{ route('painel.linhas.index') }}">Linhas e Categorias</a>
            </li>
            <li @if(Tools::routeIs('painel.produtos*')) class="active" @endif>
                <a href="{{ route('painel.produtos.index') }}">Produtos</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.empresa.index', 'painel.empresa.imagens*', 'painel.empresa.diferenciais*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Empresa <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.empresa.index')) class="active" @endif>
                <a href="{{ route('painel.empresa.index') }}">Empresa</a>
            </li>
            <li @if(Tools::routeIs('painel.empresa.imagens*')) class="active" @endif>
                <a href="{{ route('painel.empresa.imagens.index') }}">Imagens</a>
            </li>
            <li @if(Tools::routeIs('painel.empresa.diferenciais*')) class="active" @endif>
                <a href="{{ route('painel.empresa.diferenciais.index') }}">Diferenciais</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.categorias-novidades*', 'painel.novidades*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Newsletter <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.categorias-novidades*')) class="active" @endif>
                <a href="{{ route('painel.categorias-novidades.index') }}">Categorias</a>
            </li>
            <li @if(Tools::routeIs('painel.novidades*')) class="active" @endif>
                <a href="{{ route('painel.novidades.index') }}">Newsletter</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.clientes*')) class="active" @endif>
        <a href="{{ route('painel.clientes.index') }}">Clientes</a>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.orcamentos*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Orçamentos
            @if($orcamentosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $orcamentosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.orcamentos.*')) class="active" @endif>
                <a href="{{ route('painel.orcamentos.index') }}">
                    Orçamentos Recebidos
                    @if($orcamentosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $orcamentosNaoLidos }}</span>
                    @endif
                </a>
            </li>
            <li @if(Tools::routeIs('painel.orcamentos-contatos*')) class="active" @endif>
                <a href="{{ route('painel.orcamentos-contatos.index') }}">Contatos (E-mails)</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.contato*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
            <li @if(Tools::routeIs('painel.newsletter.index')) class="active" @endif>
                <a href="{{ route('painel.newsletter.index') }}">Cadastros Newsletter</a>
            </li>
        </ul>
    </li>

</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/cropperjs/dist/cropper.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/cropperjs/dist/cropper.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>

</body>
</html>