laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('home/produtos', 'HomeController@getProdutosHome')->name('getProdutosHome');
    Route::get('home/marcas', 'HomeController@getMarcasHome')->name('getMarcasHome');
    Route::post('newsletter', 'HomeController@postNewsletter')->name('newsletter.post');
    Route::get('produtos/{linha}', 'ProdutosController@index')->name('produtos'); //ok
    Route::get('produtos/{linha}/produto/{produto}', 'ProdutosController@showProduto')->name('produtos.show');
    Route::get('produtos/{linha}/busca', 'ProdutosController@busca')->name('produtos.busca'); //ok
    Route::get('produtos/{linha}/lancamentos', 'ProdutosController@filtroLancamentos')->name('produtos.lancamentos');
    Route::get('produtos/{linha}/getProdutos', 'ProdutosController@getProdutos')->name('produtos.getProdutos');
    Route::get('produtos/{linha}/categorias', 'ProdutosController@indexCategorias')->name('produtos.categorias');
    Route::get('produtos/{linha}/categorias/letra/{letra}', 'ProdutosController@filtroLetras')->name('produtos.letra');
    Route::get('produtos/{linha}/marcas/{marca}', 'ProdutosController@filtroMarcas')->name('produtos.marcas');
    Route::get('produtos/{linha}/{categoria}/{marca_slug?}', 'ProdutosController@filtro')->name('produtos.filtro');
    Route::get('produtos/pdf/{produto}', 'ProdutosController@openPdf')->name('produtos.pdf');
    Route::get('orcamentos', 'OrcamentosController@index')->name('orcamentos');
    Route::post('orcamentos/adicionar/{linha}/{produto}', 'OrcamentosController@adicionar')->name('orcamentos.adicionar');
    Route::get('orcamentos/atualizar/{produto}', 'OrcamentosController@atualizar')->name('orcamentos.atualizar');
    Route::get('orcamentos/excluir/{produto}', 'OrcamentosController@excluir')->name('orcamentos.excluir');
    Route::get('orcamentos/{cliente}', 'OrcamentosController@post')->name('orcamentos.post');
    Route::get('marcas', 'MarcasController@index')->name('marcas');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('novidades', 'NovidadesController@index')->name('novidades');
    Route::get('novidades/{novidade}', 'NovidadesController@show')->name('novidades.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('contato-footer', 'ContatoController@postFooter')->name('contato-footer.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('busca', 'BuscaController@buscar')->name('busca'); //ok
    Route::get('busca/{linha}/categorias/{letra}', 'BuscaController@getCategorias')->name('getCategorias'); //ok
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Auth Clientes
    Route::group([
        'prefix'    => 'cliente',
        'namespace' => 'Cliente'
    ], function () {
        Route::post('login', 'AuthController@login')->name('cliente.login');
        Route::get('logout', 'AuthController@logout')->name('cliente.logout');
        Route::post('cadastro', 'AuthController@create')->name('cliente.cadastro');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('home-banners', 'HomeBannersController');
        Route::resource('home-destaques', 'HomeDestaquesController', ['only' => ['index', 'update']]);
        Route::resource('home-diferenciais', 'HomeDiferenciaisController');
        Route::resource('marcas', 'MarcasController');
        Route::get('linhas', 'LinhasController@index')->name('painel.linhas.index');
        Route::resource('linhas.categorias', 'CategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/linhas/{linha}/categorias', 'ProdutosController@getCategorias')->name('painel.produtos.linhas.categorias');
        Route::get('produtos/{produto}/desenho/delete', 'ProdutosController@deleteDesenho')->name('painel.produtos.desenho.delete');
        Route::get('produtos/{produto}/manual/delete', 'ProdutosController@deleteManual')->name('painel.produtos.manual.delete');
        Route::get('produtos/{produto}/variacoes/delete', 'ProdutosController@deleteImagem')->name('painel.produtos.variacoes.delete');
        Route::resource('clientes', 'ClientesController', ['only' => ['index', 'destroy']]);
        Route::get('clientes/export', 'ClientesController@export')->name('painel.clientes.export');
        Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::get('empresa/imagens/clear', [
            'as'   => 'painel.empresa.imagens.clear',
            'uses' => 'EmpresaImagensController@clear'
        ]);
        Route::resource('empresa/imagens', 'EmpresaImagensController', ['parameters' => ['imagens' => 'empresa_imagens']]);
        Route::resource('empresa/diferenciais', 'EmpresaDiferenciaisController');
        Route::resource('categorias-novidades', 'CategoriasNovidadesController');
        Route::resource('novidades', 'NovidadesController');
        Route::get('orcamentos/{orcamento}/toggle', ['as' => 'painel.orcamentos.toggle', 'uses' => 'OrcamentosController@toggle']);
        Route::resource('orcamentos', 'OrcamentosController');
        Route::resource('orcamentos-contatos', 'ContatosOrcamentosController');

        Route::get('newsletter', 'NewsletterController@index')->name('painel.newsletter.index');
        Route::get('newsletter/export', 'NewsletterController@export')->name('painel.newsletter.export');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:cache');
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('clear-compiled');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Models/Orcamento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Orcamento extends Model
{
    protected $table = 'orcamentos';

    protected $guarded = ['id'];

    protected $casts = [
        'itens' => 'array'
    ];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function getCreatedAtOrderAttribute()
    {
        return \Carbon\Carbon::createFromFormat('d/m/Y', $this->created_at)->format('Y-m-d');
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }

    public function scopeCliente($query, $id)
    {
        return $query->where('cliente_id', $id);
    }

    public function produtos()
    {
        return $this->hasMany('App\Models\OrcamentoProduto', 'orcamento_id');
    }
}

laravel/app/Http/Controllers/OrcamentosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cliente;
use App\Models\Contato;
use App\Models\ContatoOrcamento;
use App\Models\Linha;
use App\Models\Orcamento;
use App\Models\Produto;
use Illuminate\Support\Facades\Mail;

class OrcamentosController extends Controller
{
    public function index()
    {
        // session()->forget('orcamento');
        $produtos = session()->has('orcamento') ? session()->get('orcamento') : [];

        return view('frontend.orcamentos', compact('produtos'));
    }

    public function adicionar($linha_slug, $produto_slug)
    {
        $produto = Produto::where('slug', $produto_slug)->first();

        if (!$produto) {
            return response()->json('Produto não encontrado.', 500);
        }

        $orcamento = session()->get('orcamento');

        // se o orcamento está vazio, primeiro produto a ser incluso:
        if (!$orcamento) {
            $orcamento = [
                $produto_slug => [
                    'id' => $produto->id,
                    'linha_slug' => $linha_slug,
                    'slug' => $produto->slug,
                    'titulo' => $produto->titulo,
                    'capa' => $produto->capa,
                    'codigo' => $produto->codigo,
                    'quantidade' => 1
                ]
            ];
            session()->put('orcamento', $orcamento);

            $quantidadeTotal = 0;
            foreach (session()->get('orcamento') as $orcamento) {
                $quantidadeTotal += $orcamento['quantidade'];
            }

            return response()->json($quantidadeTotal);
        };

        // se o orcamento NÃO está vazio, verifica se o produto existe e adiciona na quantidade:
        if (isset($orcamento[$produto_slug])) {
            $orcamento[$produto_slug]['quantidade']++;
            session()->put('orcamento', $orcamento);

            $quantidadeTotal = 0;
            foreach (session()->get('orcamento') as $orcamento) {
                $quantidadeTotal += $orcamento['quantidade'];
            }

            return response()->json($quantidadeTotal);
        };

        // se o produto não existe no orcamento, adiciona o produto com quantidade = 1:
        $orcamento[$produto_slug] = [
            'id' => $produto->id,
            'linha_slug' => $linha_slug,
            'slug' => $produto->slug,
            'titulo' => $produto->titulo,
            'capa' => $produto->capa,
            'codigo' => $produto->codigo,
            'quantidade' => 1
        ];

        session()->put('orcamento', $orcamento);

        $quantidadeTotal = 0;
        foreach (session()->get('orcamento') as $orcamento) {
            $quantidadeTotal += $orcamento['quantidade'];
        }

        return response()->json($quantidadeTotal);
    }

    public function atualizar($produto_slug)
    {
        $quantidade = $_GET['quantidade'];

        $produtos = session('orcamento');
        foreach ($produtos as $key => $value) {
            if ($value['slug'] == $produto_slug) {
                // dd($produtos[$key]['quantidade']);
                $produtos[$key]['quantidade'] = $quantidade;
            }
        }
        session()->put('orcamento', $produtos);

        return response()->json(['produto' => $produto_slug]);
    }

    public function excluir($produto_slug)
    {
        $produtos = session('orcamento');
        foreach ($produtos as $key => $value) {
            if ($value['slug'] == $produto_slug) {
                unset($produtos[$key]);
            }
        }
        session()->put('orcamento', $produtos);

        return redirect()->back();
    }

    public function post($cliente_id)
    {
        $cliente = Cliente::where('id', $cliente_id)->first();
        $produtos = session('orcamento');

        $anterior = Orcamento::orderBy('id', 'desc')->first();
        if (isset($anterior)) {
            $proximo = ContatoOrcamento::where('id', '>', $anterior->contato_id)->first();
            if (isset($proximo)) {
                $input = array(
                    'cliente_id' => $cliente->id,
                    'itens' => $produtos,
                    'lido' => 0,
                    'contato_id' => $proximo->id,
                );
            } else {
                $contato = ContatoOrcamento::first();
                $input = array(
                    'cliente_id' => $cliente->id,
                    'itens' => $produtos,
                    'lido' => 0,
                    'contato_id' => $contato->id,
                );
            }
        } else {
            $contato = ContatoOrcamento::first();
            $input = array(
                'cliente_id' => $cliente->id,
                'itens' => $produtos,
                'lido' => 0,
                'contato_id' => $contato->id,
            );
        }

        $orcamento = Orcamento::create($input);
        $this->sendMail($orcamento);

        session()->forget('orcamento');

        return redirect()->back()->with('success', "Pedido de orçamento enviado com sucesso!");
    }

    private function sendMail($orcamento)
    {
        $contato = ContatoOrcamento::where('id', $orcamento->contato_id)->first();
        if (!$email = $contato->email) {
            return false;
        }

        $cliente = Cliente::where('id', $orcamento['cliente_id'])->first();
        $produtos = $orcamento['itens'];

        Mail::send('emails.orcamento', ['cliente' => $cliente, 'produtos' => $produtos], function ($m) use ($email, $cliente) {
            $m->to($email, config('app.name'))
                ->subject('[ORÇAMENTO] ' . config('app.name'))
                ->replyTo($cliente['email'], $cliente['nome']);
        });
    }
}

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/CategoriasNovidadesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoriasNovidadesRequest;
use App\Models\CategoriaNovidade;

class CategoriasNovidadesController extends Controller
{
    public function index()
    {
        $categorias = CategoriaNovidade::orderBy('titulo', 'desc')->get();

        return view('painel.novidades.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.novidades.categorias.create');
    }

    public function store(CategoriasNovidadesRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $count = count(CategoriaNovidade::where('slug', $input['slug'])->get());

            if ($count == 0) {
                CategoriaNovidade::create($input);
            } else {
                return back()->withErrors(['Erro ao adicionar registro: Verifique se esse registro já existe']);
            }

            return redirect()->route('painel.categorias-novidades.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(CategoriaNovidade $categoria)
    {
        return view('painel.novidades.categorias.edit', compact('categoria'));
    }

    public function update(CategoriasNovidadesRequest $request, CategoriaNovidade $categoria)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $categoria->update($input);

            return redirect()->route('painel.categorias-novidades.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(CategoriaNovidade $categoria)
    {
        try {
            $categoria->delete();

            return redirect()->route('painel.categorias-novidades.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/orcamentos/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>Orçamentos Recebidos</h2>
</legend>

@if(!count($orcamentos))
<div class="alert alert-warning" role="alert">Nenhuma mensagem recebida.</div>
@else
<table class="table table-striped table-bordered table-hover data-table">
    <thead>
        <tr>
            <th>Data do pedido</th>
            <th>Cliente</th>
            <th>Itens do pedido</th>
            <th>E-mail enviado para:</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($orcamentos as $orcamento)
        <tr class="tr-row @if(!$orcamento->lido) warning @endif">
            <td data-order="{{ $orcamento->created_at_order }}">{{ $orcamento->created_at }}</td>
            @php
            $cliente = $clientes->find($orcamento->cliente_id)->nome;
            @endphp
            <td style="text-transform: capitalize;">{{ $cliente }}</td>
            <td>
                <table style="width: 100%;">
                    <thead style="border-bottom:1px solid #e5e5e5">
                        <tr>
                            <td style="font-weight:600;width:15%">Código</td>
                            <td style="font-weight:600;width:65%">Título</td>
                            <td style="text-align: center;font-weight:600;width:20%">Quantidade</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($orcamento->itens as $item)
                        <tr>
                            <td style="width:15%">{{ $item['codigo'] }}</td>
                            <td style="width:65%">{{ $item['titulo'] }}</td>
                            <td style="text-align:center;width:20%">{{ $item['quantidade'] }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </td>
            @if($orcamento->contato_id != null)
            @php
            $contato = $contatos->find($orcamento->contato_id)->email;
            @endphp

            @if($contato)
            <td>{{ $contato }}</td>
            @endif
            
            @else
            <td>N/A</td>
            @endif
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.orcamentos.destroy', $orcamento->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.orcamentos.show', $orcamento->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Ler mensagem
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

                    <a href="{{ route('painel.orcamentos.toggle', $orcamento->id) }}" class="btn btn-sm pull-left {{ ($orcamento->lido ? 'btn-warning' : 'btn-success') }}">
                        <span class="glyphicon small {{ ($orcamento->lido ? 'glyphicon-repeat' : 'glyphicon-ok') }}"></span>
                    </a>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>

        @endforeach
    </tbody>
</table>
@endif

@stop

laravel/resources/views/painel/orcamentos/show.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2>Orçamentos Recebidos</h2>
</legend>

<div class="form-group">
    <label>Data do pedido</label>
    <div class="well">{{ $orcamento->created_at }}</div>
</div>

<div class="form-group">
    <label>Cliente</label>
    <div class="well" style="text-transform: capitalize;">{{ $cliente->nome }}</div>
    <div class="well">{{ $cliente->email }}</div>
    @if($cliente->telefone)
    <div class="well">{{ $cliente->telefone }}</div>
    @endif
    @if($cliente->empresa)
    <div class="well">{{ $cliente->empresa }}</div>
    @endif
</div>

<div class="form-group">
    <label>Itens do pedido</label>
    <div class="well">
        <table style="width: 100%;">
            <thead style="border-bottom:1px solid #95A5A6">
                <tr>
                    <td style="font-weight:600">Código</td>
                    <td style="font-weight:600">Título</td>
                    <td style="text-align: center;font-weight:600";">Quantidade</td>
                </tr>
            </thead>
            <tbody>
                @foreach($orcamento->itens as $item)
                <tr>
                    <td>{{ $item['codigo'] }}</td>
                    <td>{{ $item['titulo'] }}</td>
                    <td style="text-align: center;">{{ $item['quantidade'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

<a href="{{ route('painel.orcamentos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

@stop